EXCLUDED_FOLDER_NAMES = {"__pycache__"}
DYNAMIC_ROUTE_PREFIX = "dynamic__"
GROUP_ROUTE_PREFIX = "group__"

CLIENT_ROUTE_INDEX_FILENAME = "page.py"
CLIENT_ROUTE_LAYOUT_FILENAME = "layout.py"
CLIENT_ROOT_ROUTER_PREFIX = "/flect"
CLIENT_ROUTE_ROUTER_PATH = "/_route/"
CLIENT_LAYOUT_ROUTER_SUFFIX = "_layout/"

SERVER_API_ROUTE_FILENAME = "route.py"
SERVER_API_ROUTE_METHODS = {"GET", "POST"}
