name: release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Release version'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python
      - uses: ./.github/actions/setup-npm

      - run: pnpm build
      - run: rye build
      - run: rye publish --token ${{ secrets.PYPI_TOKEN }} -y
