name: test

on: [push, pull_request]

jobs:
  test:
    name: test ${{ matrix.python-version }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        python-version: ['3.9', '3.10', '3.11', '3.12']

    runs-on: ${{ matrix.os }}-latest

    env:
      PYTHON: ${{ matrix.python-version }}
      OS: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - run: sed '/-e/d' requirements-dev.lock > requirements.txt
      - run: pip install -r requirements.txt
      - run: pip install -e .

      - run: export PYTHONPATH=docs/src && coverage run -m pytest
      # display coverage and fail if it's below 80%, which shouldn't happen
      - run: coverage report --fail-under=80

      - run: coverage xml

      - uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          env_vars: PYTHON,OS
